spring:
  application:
    name : uploads
server:
  port: 9007
  servlet: 
    context-path: /uploadsV1

# access key = AKIAZPB7IA3JLDLLWAUD
# secret key = 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
aws:
  accessKey: AKIAZPB7IA3JLDLLWAUD
  region: us-east-1
  s3:
  bucket: tutor-student-profile-bucket
  url: https://aws-upload-bucket-123456789.s3.amazonaws.com/   

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
